### ISSUE TITLE
Can't open maps demo project

### ISSUE THREAD

**Issue by evgenypopov2** [cuba-platform/maps-addon-demo#1]
I loaded a maps demo project but cannot open it because of getting error 
`Could not GET 'https://repo.cuba-platform.com/content/groups/premium/com/haulmont/addon/maps/maps-global/1.1-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden`
I have a commercial subscription to CUBA Studio and don't want to switch to trial.
What should I do?

**Comment by glebshalyganov** [comment]
Solved in the CUBA forum's [topic](https://www.cuba-platform.com/discuss/t/cant-open-cuba-maps-demo-project/10056).
